In [9]:
import torch.nn.utils.prune as prune
from FaceLandmarkDetection.src.quantization.helper import *

In [2]:
random_seed = 0
num_classes = 136
cuda_device = torch.device("cuda:0")
cpu_device = torch.device("cpu:0")

model_dir = "checkpoints"
model_filename = "resnet18_FLM.pt"
model_filepath = os.path.join(model_dir, model_filename)
set_random_seeds(random_seed=random_seed)

In [3]:
# Create an untrained model.
model = create_model(num_classes=num_classes)
train_dataset, val_dataset = get_data()
train_loader = make_loader(train_dataset, 64)
val_loader = make_loader(val_dataset, 32)

1111


In [4]:
model = load_model(model=model, model_filepath=model_filepath, device=cpu_device)

In [5]:
module = model.conv1
print(list(module.named_parameters()))

[('weight', Parameter containing:
tensor([[[[ 0.0967,  0.0468,  0.1814,  ..., -0.1097, -0.0182, -0.0594],
          [-0.0778,  0.0543,  0.1558,  ..., -0.0382, -0.1938,  0.0518],
          [ 0.1366,  0.0528,  0.0694,  ..., -0.0286, -0.0990, -0.0428],
          ...,
          [ 0.0738,  0.1917,  0.0005,  ..., -0.2320, -0.0540, -0.0515],
          [ 0.1891,  0.0243,  0.0659,  ..., -0.0716,  0.0362,  0.0614],
          [ 0.1064,  0.1939,  0.2091,  ..., -0.0244, -0.0978, -0.1774]]],


        [[[ 0.1092,  0.0919,  0.0567,  ..., -0.0969,  0.0725,  0.1699],
          [-0.1208,  0.0059,  0.0228,  ..., -0.1751, -0.0929, -0.0746],
          [ 0.0866, -0.0080, -0.0398,  ..., -0.1616, -0.0858, -0.0612],
          ...,
          [ 0.1268,  0.1058,  0.1897,  ...,  0.0847, -0.0484,  0.0984],
          [ 0.1092,  0.0135,  0.0963,  ...,  0.1790,  0.1162,  0.0350],
          [ 0.0162,  0.1458,  0.1452,  ...,  0.1125,  0.0016,  0.0655]]],


        [[[ 0.0383, -0.0722, -0.0494,  ...,  0.0340, -0.1325,  0

In [6]:
print(list(module.named_buffers()))

[]


In [10]:
prune.random_unstructured(module, name="weight", amount=0.3)

Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)

In [11]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.0967,  0.0468,  0.1814,  ..., -0.1097, -0.0182, -0.0594],
          [-0.0778,  0.0543,  0.1558,  ..., -0.0382, -0.1938,  0.0518],
          [ 0.1366,  0.0528,  0.0694,  ..., -0.0286, -0.0990, -0.0428],
          ...,
          [ 0.0738,  0.1917,  0.0005,  ..., -0.2320, -0.0540, -0.0515],
          [ 0.1891,  0.0243,  0.0659,  ..., -0.0716,  0.0362,  0.0614],
          [ 0.1064,  0.1939,  0.2091,  ..., -0.0244, -0.0978, -0.1774]]],


        [[[ 0.1092,  0.0919,  0.0567,  ..., -0.0969,  0.0725,  0.1699],
          [-0.1208,  0.0059,  0.0228,  ..., -0.1751, -0.0929, -0.0746],
          [ 0.0866, -0.0080, -0.0398,  ..., -0.1616, -0.0858, -0.0612],
          ...,
          [ 0.1268,  0.1058,  0.1897,  ...,  0.0847, -0.0484,  0.0984],
          [ 0.1092,  0.0135,  0.0963,  ...,  0.1790,  0.1162,  0.0350],
          [ 0.0162,  0.1458,  0.1452,  ...,  0.1125,  0.0016,  0.0655]]],


        [[[ 0.0383, -0.0722, -0.0494,  ...,  0.0340, -0.132

In [12]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[0., 1., 1.,  ..., 0., 1., 0.],
          [1., 1., 1.,  ..., 0., 1., 0.],
          [0., 1., 1.,  ..., 1., 0., 1.],
          ...,
          [1., 1., 1.,  ..., 0., 0., 1.],
          [1., 1., 0.,  ..., 1., 0., 1.],
          [1., 1., 0.,  ..., 1., 1., 0.]]],


        [[[1., 0., 1.,  ..., 1., 0., 1.],
          [1., 1., 1.,  ..., 1., 1., 0.],
          [0., 0., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 0., 0.,  ..., 0., 1., 1.],
          [0., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 0., 1., 1.]]],


        [[[0., 0., 0.,  ..., 1., 0., 1.],
          [1., 0., 1.,  ..., 1., 0., 1.],
          [0., 1., 1.,  ..., 0., 0., 1.],
          ...,
          [1., 1., 1.,  ..., 0., 1., 1.],
          [1., 0., 1.,  ..., 0., 1., 1.],
          [0., 0., 0.,  ..., 1., 0., 1.]]],


        ...,


        [[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 0.,  ..., 1., 0., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [0.,

In [13]:
print(module.weight)

tensor([[[[ 0.0000,  0.0468,  0.1814,  ..., -0.0000, -0.0182, -0.0000],
          [-0.0778,  0.0543,  0.1558,  ..., -0.0000, -0.1938,  0.0000],
          [ 0.0000,  0.0528,  0.0694,  ..., -0.0286, -0.0000, -0.0428],
          ...,
          [ 0.0738,  0.1917,  0.0005,  ..., -0.0000, -0.0000, -0.0515],
          [ 0.1891,  0.0243,  0.0000,  ..., -0.0716,  0.0000,  0.0614],
          [ 0.1064,  0.1939,  0.0000,  ..., -0.0244, -0.0978, -0.0000]]],


        [[[ 0.1092,  0.0000,  0.0567,  ..., -0.0969,  0.0000,  0.1699],
          [-0.1208,  0.0059,  0.0228,  ..., -0.1751, -0.0929, -0.0000],
          [ 0.0000, -0.0000, -0.0398,  ..., -0.1616, -0.0858, -0.0612],
          ...,
          [ 0.1268,  0.0000,  0.0000,  ...,  0.0000, -0.0484,  0.0984],
          [ 0.0000,  0.0135,  0.0963,  ...,  0.1790,  0.1162,  0.0350],
          [ 0.0162,  0.1458,  0.1452,  ...,  0.0000,  0.0016,  0.0655]]],


        [[[ 0.0000, -0.0000, -0.0000,  ...,  0.0340, -0.0000,  0.0605],
          [-0.1214, -0.000

Finally, pruning is applied prior to each forward pass using PyTorch’s forward_pre_hooks. Specifically, when the module is pruned, as we have done here, it will acquire a forward_pre_hook for each parameter associated with it that gets pruned. In this case, since we have so far only pruned the original parameter named weight, only one hook will be present.

In [14]:
print(module._forward_pre_hooks)

OrderedDict([(0, <torch.nn.utils.prune.RandomUnstructured object at 0x7fae529acd60>)])


ITERATIVE

In [15]:
prune.ln_structured(module, name="weight", amount=0.5, n=2, dim=0)

# As we can verify, this will zero out all the connections corresponding to
# 50% (3 out of 6) of the channels, while preserving the action of the
# previous mask.
print(module.weight)

tensor([[[[ 0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000, -0.0000],
          [-0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000, -0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000, -0.0000],
          [ 0.0000,  0.0000,  0.0000,  ..., -0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000, -0.0000]]],


        [[[ 0.1092,  0.0000,  0.0567,  ..., -0.0969,  0.0000,  0.1699],
          [-0.1208,  0.0059,  0.0228,  ..., -0.1751, -0.0929, -0.0000],
          [ 0.0000, -0.0000, -0.0398,  ..., -0.1616, -0.0858, -0.0612],
          ...,
          [ 0.1268,  0.0000,  0.0000,  ...,  0.0000, -0.0484,  0.0984],
          [ 0.0000,  0.0135,  0.0963,  ...,  0.1790,  0.1162,  0.0350],
          [ 0.0162,  0.1458,  0.1452,  ...,  0.0000,  0.0016,  0.0655]]],


        [[[ 0.0000, -0.0000, -0.0000,  ...,  0.0000, -0.0000,  0.0000],
          [-0.0000, -0.000

In [16]:
for hook in module._forward_pre_hooks.values():
    if hook._tensor_name == "weight":  # select out the correct hook
        break

print(list(hook))  # pruning history in the container

[<torch.nn.utils.prune.RandomUnstructured object at 0x7fae529acd60>, <torch.nn.utils.prune.LnStructured object at 0x7fae517c9910>]


use the remove functionality from torch.nn.utils.prune. Note that this doesn’t undo the pruning, as if it never happened. It simply makes it permanent, instead, by reassigning the parameter weight to the model parameters, in its pruned version.

In [17]:
prune.remove(module, 'weight')
print(list(module.named_parameters()))

[('weight', Parameter containing:
tensor([[[[ 0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000, -0.0000],
          [-0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000, -0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000, -0.0000],
          [ 0.0000,  0.0000,  0.0000,  ..., -0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ..., -0.0000, -0.0000, -0.0000]]],


        [[[ 0.1092,  0.0000,  0.0567,  ..., -0.0969,  0.0000,  0.1699],
          [-0.1208,  0.0059,  0.0228,  ..., -0.1751, -0.0929, -0.0000],
          [ 0.0000, -0.0000, -0.0398,  ..., -0.1616, -0.0858, -0.0612],
          ...,
          [ 0.1268,  0.0000,  0.0000,  ...,  0.0000, -0.0484,  0.0984],
          [ 0.0000,  0.0135,  0.0963,  ...,  0.1790,  0.1162,  0.0350],
          [ 0.0162,  0.1458,  0.1452,  ...,  0.0000,  0.0016,  0.0655]]],


        [[[ 0.0000, -0.0000, -0.0000,  ...,  0.0000, -0.0000,  0

In [18]:
print(list(module.named_buffers()))

[]


GLOBAL PRUNING

In [28]:
model = create_model(num_classes=num_classes)
model = load_model(model=model, model_filepath=model_filepath, device=cpu_device)

In [29]:
evaluate_model(model=model, test_loader=val_loader, device=cpu_device, criterion=nn.MSELoss())

0.02315837775801753

In [22]:
parameters_to_prune = (
    (model.conv1, 'weight'),
    (model.layer1[0].conv1, 'weight'),
    (model.layer1[0].conv2, 'weight'),
    (model.layer1[1].conv1, 'weight'),
    (model.layer1[1].conv2, 'weight'),
    (model.layer2[0].conv1, 'weight'),
    (model.layer2[0].conv2, 'weight'),
    (model.layer2[1].conv1, 'weight'),
    (model.layer2[1].conv2, 'weight'),
    (model.layer3[0].conv1, 'weight'),
    (model.layer3[0].conv2, 'weight'),
    (model.layer3[1].conv1, 'weight'),
    (model.layer3[1].conv2, 'weight'),
    (model.layer4[0].conv1, 'weight'),
    (model.layer4[0].conv2, 'weight'),
    (model.layer4[1].conv1, 'weight'),
    (model.layer4[1].conv2, 'weight'),
    (model.fc, 'weight'),
)

prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.2,
)

In [23]:
parameters_to_prune, len(parameters_to_prune)

(((Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False),
   'weight'),
  (Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),
   'weight'),
  (Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),
   'weight'),
  (Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),
   'weight'),
  (Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),
   'weight'),
  (Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False),
   'weight'),
  (Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),
   'weight'),
  (Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),
   'weight'),
  (Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),
   'weight'),
  (Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False),
   'weight'),
  (Conv2d(256, 256, kernel_size=

In [24]:
print(list(model.named_parameters()))

99, -0.3231,
        -0.3468, -0.3553, -0.3537, -0.3315, -0.3713, -0.1091, -0.0959, -0.0258,
        -0.2756, -0.2808, -0.2012, -0.2812, -0.1991, -0.3948, -0.2257, -0.2469,
        -0.4211, -0.2110, -0.4670, -0.3069, -0.3549, -0.2337, -0.0612, -0.1321,
        -0.2968, -0.1870, -0.2316, -0.0686, -0.3113, -0.2895, -0.3149, -0.2686,
        -0.2081, -0.2096, -0.3011, -0.1810, -0.0227, -0.3873, -0.2665, -0.0225,
        -0.2973, -0.0973, -0.2980, -0.3219, -0.2926, -0.3196, -0.4332, -0.1980,
        -0.2117, -0.2302, -0.0980, -0.2344, -0.2154, -0.2921, -0.0350, -0.3361,
        -0.2620, -0.2188, -0.1566, -0.1795, -0.2726, -0.4103,  0.0413, -0.1507,
        -0.2552, -0.3137, -0.2466, -0.2961, -0.0938, -0.1481, -0.2129, -0.5480,
        -0.2915, -0.2802, -0.5077, -0.1306, -0.1862, -0.2400, -0.4362, -0.3017,
        -0.1633, -0.3447, -0.1047, -0.2846, -0.1244, -0.3036, -0.2404, -0.2333,
        -0.2494, -0.1866, -0.3294, -0.1677, -0.2540, -0.1295, -0.0512, -0.1966,
        -0.2801, -0.1702, -

In [25]:
sparsed = 0
total = 0
for param in parameters_to_prune:
    sparsed += float(torch.sum(param[0].weight == 0))
    total += float(param[0].weight.nelement())
    prune.remove(param[0], "weight")
    print("Sparsity in " +str(param[0])+": {:.2f}%".format(
        100. * float(torch.sum(param[0].weight == 0))
        / float(param[0].weight.nelement())
    ))
    
print(
    "Global sparsity: {:.2f}%".format(
        100. * sparsed / total
    ))

Sparsity in Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False): 2.46%
Sparsity in Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False): 21.34%
Sparsity in Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False): 10.19%
Sparsity in Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False): 9.85%
Sparsity in Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False): 10.06%
Sparsity in Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False): 11.12%
Sparsity in Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False): 12.89%
Sparsity in Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False): 12.74%
Sparsity in Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False): 13.23%
Sparsity in Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False): 14.39%
Sparsity in Co

In [26]:
print_size_of_model(model)

Size (MB): 45.075501


no reduction in model size, only weights updated to 0 

In [27]:
evaluate_model(model=model, test_loader=val_loader, device=cpu_device, criterion=nn.MSELoss())

0.024139876099857124

EVAL LOSS NOT THAT HIGH

Pruning with NNI - Neural Network Intelligence

In [43]:
model = create_model(num_classes=num_classes)
model = load_model(model=model, model_filepath=model_filepath, device=cpu_device)

In [44]:
from nni.algorithms.compression.pytorch.pruning import LevelPruner
config_list = [{ 'sparsity': 0.2, 'op_types': ['default'] }]
pruner = LevelPruner(model, config_list)
pruned_model = pruner.compress()

In [45]:
evaluate_model(model=pruned_model, test_loader=val_loader, device=cpu_device, criterion=nn.MSELoss())

0.02452341750734024

FOR REAL CHANGE IN THE MODEL AFTER PRUNING USE MODELSPEEDUP MODULE

In [37]:
from nni.compression.pytorch import ModelSpeedup

In [49]:
prune_model_dir = "checkpoints_pruned"
prune_model_filename = "resnet18_FLM_pruned.pt"
prune_model_filepath = os.path.join(prune_model_dir, prune_model_filename)
pruner.export_model(prune_model_filepath, os.path.join(prune_model_dir, 'mask.pth'))

[2021-01-22 09:58:39] INFO (nni.compression.pytorch.compressor/MainThread) Model state_dict saved to checkpoints_pruned/resnet18_FLM_pruned.pt
[2021-01-22 09:58:39] INFO (nni.compression.pytorch.compressor/MainThread) Mask dict saved to checkpoints_pruned/mask.pth


In [51]:
pruned_model = create_model(num_classes=num_classes)
pruned_model.load_state_dict(torch.load(prune_model_filepath))
masks_file = os.path.join(prune_model_dir, 'mask.pth')

In [52]:
dummy_input = torch.randn(32,1,224,224)

In [53]:
dummy_input.shape

torch.Size([32, 1, 224, 224])

In [55]:
device = torch.device("cpu")
m_speedup = ModelSpeedup(pruned_model, dummy_input, masks_file, device)
m_speedup.speedup_model()

[2021-01-22 10:01:57] INFO (nni.compression.pytorch.speedup.compressor/MainThread) start to speed up the model
[2021-01-22 10:01:57] INFO (nni.compression.pytorch.speedup.compressor/MainThread) fix the mask conflict of the interdependent layers
[2021-01-22 10:02:06] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) {'conv1': 1, 'layer1.0.conv1': 1, 'layer1.0.conv2': 1, 'layer1.1.conv1': 1, 'layer1.1.conv2': 1, 'layer2.0.conv1': 1, 'layer2.0.conv2': 1, 'layer2.0.downsample.0': 1, 'layer2.1.conv1': 1, 'layer2.1.conv2': 1, 'layer3.0.conv1': 1, 'layer3.0.conv2': 1, 'layer3.0.downsample.0': 1, 'layer3.1.conv1': 1, 'layer3.1.conv2': 1, 'layer4.0.conv1': 1, 'layer4.0.conv2': 1, 'layer4.0.downsample.0': 1, 'layer4.1.conv1': 1, 'layer4.1.conv2': 1}
[2021-01-22 10:02:06] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers conv1 using fine-grained pruning
[2021-01-22 10:02:06] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers layer1.0.conv1 using fi

RuntimeError: The size of tensor a (56) must match the size of tensor b (64) at non-singleton dimension 0

EXISTING ISSUE. WATCH V2.0

PRUNING WITH TENSORFLOW (TFMOT) LEADS TO REAL MODEL COMPRESSION, BUT REQUIRES THE MODEL DEFINITION TO BE IN TF

ADD EXAMPLE WITH TENSORFLOW HERE